version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic
  
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - unparam
      # IATA codes are not misspellings
      - path: codes/iata\.go
        linters:
          - misspell

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

formatters:
  enable:
    - gofmt
    - goimports
